version: '3.5'
services:
  front:
    image: node:14.16.0-alpine3.13
    ports:
      - "${FRONT_PORT:-3000}:${FRONT_PORT:-3000}"
    working_dir: /app
    command: sh -c "npm install && npm run start:dev"
    env_file:
      - .env
    volumes:
      - ./front/:/app

  bot:
    image: node:14.16.0-alpine3.13
    hostname: "${BOT_HOSTNAME:-webapp}"
    ports:
      - "${BOT_PORT:-4000}:${BOT_PORT:-4000}"
    working_dir: /app
    command: sh -c "npm install && npm run start:dev"
    env_file:
      - .env
      - bot/.env
    volumes:
      - ./bot:/app

  webapp:
    image: node:14.16.0-alpine3.13
    hostname: "${WEBAPP_HOSTNAME:-webapp}"
    ports:
      - "${WEBAPP_PORT:-5000}:${WEBAPP_PORT:-5000}"
    working_dir: /app
    command: sh -c "npm install && npm run start:dev"
    volumes:
      - ./webapp/:/app

  redis:
    image: redis:6.2.1-alpine3.13
    hostname: "${REDIS_HOSTNAME:-redis}"

  ngrok:
    image: wernight/ngrok:latest
    environment:
      NGROK_LOOK_DOMAIN: "${BOT_HOSTNAME:-bot}"
      NGROK_DEBUG: "true"
      NGROK_PORT: "${BOT_PORT:-4000}"
