version: '3.5'
services:
  proxy:
    image: nginx:1.19.8-alpine
    volumes:
     - ./nginx.conf.template:/etc/nginx/templates/default.conf.template
    env_file:
      - .env
    networks:
      proxied-net:
      obs-slack-banner:
    depends_on:
      - front
      - webapp
      - bot

  front:
    image: ghcr.io/ayudante-virtual/obs-slack-banner-front:latest
    hostname: "${FRONT_HOSTNAME}"
    depends_on:
      - webapp
    env_file:
      - .env
    environment:
      PORT: ${FRONT_PORT}
    networks:
      obs-slack-banner:

  bot:
    image: ghcr.io/ayudante-virtual/obs-slack-banner-bot:latest
    hostname: "${BOT_HOSTNAME}"
    env_file:
      - .env
    depends_on:
      - webapp
    networks:
      obs-slack-banner:

  webapp:
    image: ghcr.io/ayudante-virtual/obs-slack-banner-webapp:latest
    hostname: "${WEBAPP_HOSTNAME}"
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      obs-slack-banner:

  redis:
    image: redis:6.2.1-alpine3.13
    hostname: "${REDIS_HOSTNAME}"
    networks:
      obs-slack-banner:

networks:
  obs-slack-banner:
  proxied-net:
    name: proxied-net
